#!/bin/bash

# move to projet directory
cd /home/ubuntu/

# Delete previous projet directory
# in BeforeInstall hooks, otherwise deployment fail if it exist
rm -rf ./yattblog

# clean up docker unused images
docker image prune -af

# clean up docker unused volumes
docker volume prune -f
