#!/bin/bash

# move to projet directory
cd /home/ubuntu/yattblog/

# Copy env_file dir from home to projet
cp -r /home/ubuntu/.env_file ./

# Change Owner of project directory from root to ubuntu
chown -R ubuntu:ubuntu /home/ubuntu/yattblog

# The following command update docker running containers fro prod stuff:
# If changed container w'll re-create
# If nothing stuff w'll not do.
docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d --remove-orphans && \
    sleep 5 && \
    docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec web python manage.py migrate --noinput && \
    sleep 5 && \
    docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec web python manage.py test --noinput && \
    sleep 5 && \
    docker image prune -af && \
    sleep 5 && \
    docker volume prune -f
