# Generated by Django 3.2.9 on 2021-11-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211114_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uuid',
            new_name='id',
        ),
    ]
