# Generated by Django 3.2.9 on 2021-11-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211114_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile-pic-default.jpg', upload_to='profile_pic', verbose_name='Image du profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='banner_image',
            field=models.ImageField(default='slider-1.jpg', upload_to='banner', verbose_name='Image du banner'),
        ),
    ]
