# Generated by Django 3.2.9 on 2021-11-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(help_text='Short Bio (eg. I love cats and games)', max_length=255),
        ),
    ]
