# Generated by Django 3.2.10 on 2021-12-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
